Files in this folder contains the data generated by our programme. 
As we adopt random selection method towards ambiguity problem, 
the data generated by the system may vary each time. 
Data in this file is just an example extracted from one evaluation process.
